apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: onb-us-cmpn-drct-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: onb-us-cmpn-drct-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/company_director_us
    tls: ""
  method: ""
  methods:
  - PUT
  prefix: ""
  relativeurl: /onboarding/company_director_us
