include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-vVKa

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: onb-us-cmpn-drct-fn-ea245518-e70c-4012-a10c-ee63ebe020ae
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-vVKa
  environment:
    name: onb-us-cmpn-drct-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-06T13:00:25Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: onb-us-cmpn-drct-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
      hpaMetrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 80
            type: Utilization
        type: Resource
    StrategyType: execution
  concurrency: 500
  environment:
    name: onb-us-cmpn-drct-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: onb-us-cmpn-drct-fn-ea245518-e70c-4012-a10c-ee63ebe020ae
      namespace: default
  requestsPerPod: 10000
  resources: {}
